### PR TITLE
Fix #139: Handle non-ASCII characters correctly when annotating text

### LINKED ISSUE #139: java.lang.IndexOutOfBoundsException with v0.6.0
Hi, since version 0.6.0 i have the following error on my pipeline when running a build : 

```
java.lang.IndexOutOfBoundsException
	at hudson.MarkupText.rangeCheck(MarkupText.java:276)
	at hudson.MarkupText.addMarkup(MarkupText.java:270)
	at hudson.plugins.ansicolor.ColorConsoleAnnotator$1EmitterImpl.emitHtml(ColorConsoleAnnotator.java:74)
	at hudson.plugins.ansicolor.AnsiAttributeElement.emitClose(AnsiAttributeElement.java:42)
	at hudson.plugins.ansicolor.AnsiHtmlOutputStream.closeOpenTags(AnsiHtmlOutputStream.java:107)
	at hudson.plugins.ansicolor.AnsiHtmlOutputStream.processAttributeRest(AnsiHtmlOutputStream.java:542)
	at hudson.plugins.ansicolor.AnsiOutputStream.processEscapeCommand(AnsiOutputStream.java:358)
	at hudson.plugins.ansicolor.AnsiOutputStream.write(AnsiOutputStream.java:138)
	at hudson.plugins.ansicolor.AnsiHtmlOutputStream.write(AnsiHtmlOutputStream.java:220)
	at org.apache.commons.io.output.ProxyOutputStream.write(ProxyOutputStream.java:55)
	at hudson.plugins.ansicolor.ColorConsoleAnnotator.annotate(ColorConsoleAnnotator.java:91)
	at hudson.console.ConsoleAnnotator$ConsoleAnnotatorAggregator.annotate(ConsoleAnnotator.java:108)
	at hudson.console.ConsoleAnnotationOutputStream.eol(ConsoleAnnotationOutputStream.java:148)
	at hudson.console.LineTransformationOutputStream.eol(LineTransformationOutputStream.java:60)
	at hudson.console.LineTransformationOutputStream.write(LineTransformationOutputStream.java:56)
	at java.io.FilterOutputStream.write(FilterOutputStream.java:77)
	at org.jenkinsci.plugins.workflow.log.FileLogStorage$1$1.write(FileLogStorage.java:238)
	at java.io.FilterOutputStream.write(FilterOutputStream.java:125)
	at org.apache.commons.io.output.ProxyOutputStream.write(ProxyOutputStream.java:90)
	at org.kohsuke.stapler.framework.io.LargeText$HeadMark.moveTo(LargeText.java:314)
	at org.kohsuke.stapler.framework.io.LargeText.writeLogTo(LargeText.java:229)
	at hudson.console.AnnotatedLargeText.writeRawLogTo(AnnotatedLargeText.java:163)
	at org.jenkinsci.plugins.workflow.log.FileLogStorage$1.writeHtmlTo(FileLogStorage.java:203)
	at hudson.console.AnnotatedLargeText.writeLogTo(AnnotatedLargeText.java:144)
	at org.kohsuke.stapler.framework.io.LargeText.doProgressText(LargeText.java:264)
	at hudson.console.AnnotatedLargeText.doProgressiveHtml(AnnotatedLargeText.java:92)
	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627)
	at org.kohsuke.stapler.Function$MethodFunction.invoke(Function.java:343)
	at org.kohsuke.stapler.Function.bindAndInvoke(Function.java:184)
	at org.kohsuke.stapler.Function.bindAndInvokeAndServeResponse(Function.java:117)
	at org.kohsuke.stapler.MetaClass$1.doDispatch(MetaClass.java:130)
	at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:58)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:739)
Caused: javax.servlet.ServletException
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:789)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:870)
	at org.kohsuke.stapler.MetaClass$3.doDispatch(MetaClass.java:212)
	at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:58)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:739)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:870)
	at org.kohsuke.stapler.MetaClass$10.dispatch(MetaClass.java:384)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:739)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:870)
	at org.kohsuke.stapler.MetaClass$5.doDispatch(MetaClass.java:253)
	at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:58)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:739)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:870)
	at org.kohsuke.stapler.MetaClass$5.doDispatch(MetaClass.java:253)
	at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:58)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:739)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:870)
	at org.kohsuke.stapler.MetaClass$5.doDispatch(MetaClass.java:253)
	at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:58)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:739)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:870)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:668)
	at org.kohsuke.stapler.Stapler.service(Stapler.java:238)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:865)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1655)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:154)
	at org.jenkinsci.plugins.ssegateway.Endpoint$SSEListenChannelFilter.doFilter(Endpoint.java:243)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:151)
	at io.jenkins.blueocean.ResourceCacheControl.doFilter(ResourceCacheControl.java:134)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:151)
	at io.jenkins.blueocean.auth.jwt.impl.JwtAuthenticationFilter.doFilter(JwtAuthenticationFilter.java:61)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:151)
	at jenkins.telemetry.impl.UserLanguages$AcceptLanguageFilter.doFilter(UserLanguages.java:128)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:151)
	at hudson.util.PluginServletFilter.doFilter(PluginServletFilter.java:157)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
	at hudson.security.csrf.CrumbFilter.doFilter(CrumbFilter.java:99)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:84)
	at hudson.security.UnwrapSecurityExceptionFilter.doFilter(UnwrapSecurityExceptionFilter.java:51)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at jenkins.security.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:117)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.providers.anonymous.AnonymousProcessingFilter.doFilter(AnonymousProcessingFilter.java:125)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.ui.rememberme.RememberMeProcessingFilter.doFilter(RememberMeProcessingFilter.java:142)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.ui.AbstractProcessingFilter.doFilter(AbstractProcessingFilter.java:271)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at jenkins.security.BasicHeaderProcessor.doFilter(BasicHeaderProcessor.java:93)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.context.HttpSessionContextIntegrationFilter.doFilter(HttpSessionContextIntegrationFilter.java:249)
	at hudson.security.HttpSessionContextIntegrationFilter2.doFilter(HttpSessionContextIntegrationFilter2.java:67)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at hudson.security.ChainedServletFilter.doFilter(ChainedServletFilter.java:90)
	at hudson.security.HudsonFilter.doFilter(HudsonFilter.java:171)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
	at org.kohsuke.stapler.compression.CompressionFilter.doFilter(CompressionFilter.java:49)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
	at hudson.util.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:82)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
	at org.kohsuke.stapler.DiagnosticThreadNameFilter.doFilter(DiagnosticThreadNameFilter.java:30)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:533)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:524)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1340)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1242)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:503)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:364)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.lang.Thread.run(Thread.java:745)
```
The pipeline still kept going but there is no more output on the console.
the error seems to always appear at the same step : 

```
def mavenVersion(){
ansiColor('xterm') {
     echo "\033[94;1m[ INFO ] Récupération du numéro de version de l'application\033[0m"
}
     env.APP_VERSION = sh script : 'grep "<version>" pom.xml | head -n 1 | grep -om1 "[0-9.]\\+"',returnStdout: true
}
```
but there is two output in colors displayed before like this one : 

```
def CleanAledaDependency(){
ansiColor('xterm') {
    echo "\033[94;1m[ INFO ] Nettoyage des dépendances  dans le cache maven et gradle\033[0m"
}
    sh 'rm -rf /home/jenkins/.m2/repository/xxx/* & rm -rf /home/jenkins/.gradle/caches/modules-2/files-2.1/xxx/*'
}
```

I am on Jenkins 2.152 with the multibranch pipeline. I have reverted back to the 0.5.3 version of the plugin.

### PR DESCRIPTION
**Pull request by dwnusbaum**
Fixes #139.

The cause of the issue is that we were using byte indices as `String` indices, which does not work when the `String` contains characters that require than one byte in the target encoding. To fix the issue, this PR keeps track of the number of multi-byte characters we've seen and how many bytes they require, and uses that information to convert the byte count obtained from `incoming.getCount()` into an index into the original text.

I originally worked on this in #137 but extracted it here so it can be reviewed independently from the less-important issues in that PR.

### CODE REVIEW

**Comment by dblock** [comment]
LGTM, needs CHANGELOG entry

**Comment by dwnusbaum** [comment]
> needs CHANGELOG entry

Good point, I'll add one in a bit.

File: src/main/java/hudson/plugins/ansicolor/ColorConsoleAnnotator.java [hunk 1]
```diff
@@ -66,29 +66,33 @@
...
             CountingOutputStream incoming = new CountingOutputStream(new AnsiHtmlOutputStream(outgoing, colorMap, emitter));
             emitter.incoming = incoming;
             try {
-                byte[] data = s.getBytes(charset);
-                for (int i = 0; i < data.length; i++) {
-                    // Do not use write(byte[]) as offsets in incoming would not be accurate.
-                    incoming.write(data[i]);
+                for (int i = 0; i < s.length(); i++) {
+                    // We write one UTF-16 code unit at a time so that our counting methods can handle multibyte characters correctly.
+                    byte[] chars = String.valueOf(s.charAt(i)).getBytes(charset);
```
[the remark this answers is not in the document]
Comment (dwnusbaum) [reply src/main/java/hudson/plugins/ansicolor/ColorConsoleAnnotator.java]: Also, maybe we need iterate through the Unicode code points rather than the UTF-16 code units in case any characters are not in the BMP? I tried adding emoji to the test case, but it looks like the emoji is converted into the replacement character for unmappable characters somewhere along the line before `annotate` is called (not sure where), so I don't think it's possible to handle it correctly here (although maybe I was doing something wrong in my test).

[the remark this answers is not in the document]
Comment (jglick) [reply src/main/java/hudson/plugins/ansicolor/ColorConsoleAnnotator.java]: I suspect this entire (`src/main/`) patch could be simplified to

```diff
-byte[] data = s.getBytes(charset);
+byte[] data = s.getBytes("US-ASCII");
```

plus deleting `charset` and the code that sets it. After all, we do not really care what any of the >U+007F characters in the log are for this purpose—we are throwing out the output and just looking for ESC and stuff, so if we send some `(byte) '?'` through it will not matter.

(Alternately, do not bother getting a `byte[]` at all, just loop over `char`s in `s` and write one `byte` for each—either the same, if ASCII, or something arbitrary like `'?'` otherwise.)

File: src/main/java/hudson/plugins/ansicolor/ColorConsoleAnnotator.java [hunk 2]
```diff
@@ -50,12 +50,10 @@
     private static final long serialVersionUID = 1;
 
     private final String colorMapName;
-    private final String charset;
```
Comment (dwnusbaum) [inline src/main/java/hudson/plugins/ansicolor/ColorConsoleAnnotator.java]: I guess this could cause issues if someone upgraded the plugin to the version with this fix and then downgraded to 0.6.0, but it's not clear to me what the lifecycle of a serialized `ConsoleAnnotator` would be to know for sure if it would matter.

File: src/main/java/hudson/plugins/ansicolor/ColorConsoleAnnotator.java (hunk 1 above)
[the remark this answers is not in the document]
Comment (dwnusbaum) [reply src/main/java/hudson/plugins/ansicolor/ColorConsoleAnnotator.java]: Ok, it seemed easiest to just switch to using US-ASCII so I did that and added an explanatory comment.

File: src/main/java/hudson/plugins/ansicolor/ColorConsoleAnnotator.java [hunk 3]
```diff
@@ -85,7 +83,14 @@ public void emitHtml(String html) {
             CountingOutputStream incoming = new CountingOutputStream(new AnsiHtmlOutputStream(outgoing, colorMap, emitter));
             emitter.incoming = incoming;
             try {
-                byte[] data = s.getBytes(charset);
+                /*
+                 * We only use AnsiHtmlOutputStream for its calls to Emitter.emitHtml when it encounters ANSI escape
+                 * sequences. The output of the stream will be discarded. We encode the String using US_ASCII because
+                 * all ANSI escape sequences can be represented in ASCII using a single byte, and any non-ASCII
+                 * characters will be replaced with '?', which is good, since it means that byte offsets will match
```
Comment (vincentisambart) [inline src/main/java/hudson/plugins/ansicolor/ColorConsoleAnnotator.java]: Sorry for commenting out of nowhere, but will that work with non-BMP characters, like emojis?
In Java, `"😀".length()` is 2 but `"😀".getBytes("US-ASCII").length` seems to be 1.

Comment (dwnusbaum) [reply src/main/java/hudson/plugins/ansicolor/ColorConsoleAnnotator.java]: Ok, non-BMP characters were broken by the earlier method because markup text was getting inserted in between the two code units of a surrogate pair in some cases. After ffb5045 they should work correctly. Here's a screenshot of running the following pipeline with that commit:

```
ansiColor {
    echo '\033[94;1m[ INFO ] 😀😀Wooh\033[0m😀NotCoolored'
} 
```
screen shot 2018-12-12 at 10 36 37

Thanks for the comment!

**Comment by dblock** [comment]
@jglick can I leave all this to you to merge/release/comment?

I haven't been using Jenkins lately ;)

File: src/main/java/hudson/plugins/ansicolor/ColorConsoleAnnotator.java (hunk 2 above)
Comment (jglick) [reply src/main/java/hudson/plugins/ansicolor/ColorConsoleAnnotator.java]: It is only serialized while a `console` page for a running build is being held open, so I do not think you need to care.
